#!/bin/bash

INPUT_LINES=$1
NUM_THREADS=$2

#echo $INPUT_LINES
#echo $NUM_THREADS

NUMBER_LINES_SPLIT_TMP=$(((INPUT_LINES + 3) / (4 * NUM_THREADS )))
NUMBER_LINES_SPLIT=$((NUMBER_LINES_SPLIT_TMP * 4))

echo $NUMBER_LINES_SPLIT